### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by x12901** [rvorias/ind_knn_ad#14]
To load model weights, I create an instance of the same model first, and then load the parameters using load_state_dict() method.

```python
model = PatchCore()
train_dataset = StreamingDataset()
test_dataset = StreamingDataset()
train_paths = "D:\\OK"
test_paths = "D:\\NG"
for root, dirs, paths in os.walk(test_paths):
    for path in paths:
        f = Image.open(os.path.join(root, path))
        test_dataset.add_pil_image(f)
# train images
for root, dirs, files in os.walk(train_paths ):
    for file in files:
        train_dataset.add_pil_image(Image.open(os.path.join(root, file)))
# model.to(device)
# model.fit(DataLoader(train_dataset))
PATH = "test.pth"
# torch.save(model.state_dict(), PATH)
print("One image testing ...")
model.load_state_dict(torch.load(PATH))
model.eval()
for test_idx in range(test_dataset.size):
    sample, *_ = test_dataset[test_idx]
    img_lvl_anom_score, pxl_lvl_anom_score = model.predict(sample.unsqueeze(0))
```

```python
C:\ProgramData\Anaconda3\envs\knn\python.exe D:/ind_knn_ad-master/test.py
One image testing ...
C:\ProgramData\Anaconda3\envs\knn\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "D:/ind_knn_ad-master/test.py", line 146, in <module>
    img_lvl_anom_score, pxl_lvl_anom_score = model.predict(sample.unsqueeze(0))
  File "D:\ind_knn_ad-master\indad\models.py", line 278, in predict
    resized_maps = [self.resize(self.average(fmap)) for fmap in feature_maps]
  File "D:\ind_knn_ad-master\indad\models.py", line 278, in <listcomp>
    resized_maps = [self.resize(self.average(fmap)) for fmap in feature_maps]
TypeError: 'NoneType' object is not callable
```

**Comment by rvorias** [comment]
Hey x12901, sorry I missed this issue. Have you checked all of the model's attributes? I'm not sure if my current model structure supports full serialization.

It appears `self.resize` and/or `self.average` are not loaded from the state dict.
