### ISSUE TITLE
Overwrite yml file but it does not exist. 

### ISSUE THREAD

**Issue by leolin65** [rvorias/ind_knn_ad#3]
Test results zipper - image_rocauc: 0.94, pixel_rocauc: 0.98
Traceback (most recent call last):
  File "D:\Code\ind_knn_ad-master\indad\run.py", line 82, in <module>
    cli_interface()
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "D:\Code\ind_knn_ad-master\indad\run.py", line 79, in cli_interface
    write_results(total_results, method)
  File "D:\Code\ind_knn_ad-master\indad\utils.py", line 65, in write_results
    with open(f"./results/{name}.yml", "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: './results/spade_26_07_2021_22_47_37.yml'

**Comment by rvorias** [comment]
Based on you last issues, you should run your commands from the main folder like this:
`.../ind_knn_ad: python indad/run.py METHOD [--dataset DATASET]`

and not like this:
`.../ind_knn_ad/indad: python run.py METHOD [--dataset DATASET]`

Most paths are hardcoded. It needs to be called from the main dir.

**Comment by leolin65** [comment]
> you should run your commands from the main folder like this:
> `.../ind_knn_ad: python indad/run.py METHOD [--dataset DATASET]`

Got it, thank you.
